// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujLAGFhHA2pfMmOfnZOmdABl33kuFSCc',
    appId: '1:995930544925:web:4520b63c55ff0de1141ff4',
    messagingSenderId: '995930544925',
    projectId: 'noteapp-2fc21',
    authDomain: 'noteapp-2fc21.firebaseapp.com',
    storageBucket: 'noteapp-2fc21.appspot.com',
    measurementId: 'G-EZ5D2YEWQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyt2NFtWJNg27LL_7I4M_hjgHJTYCgIwQ',
    appId: '1:995930544925:android:4b418f93245cb413141ff4',
    messagingSenderId: '995930544925',
    projectId: 'noteapp-2fc21',
    storageBucket: 'noteapp-2fc21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTBtNcWoSDNRJ2GCOiYDo-3FqCRY_8Tw',
    appId: '1:995930544925:ios:76ee10e96b81997a141ff4',
    messagingSenderId: '995930544925',
    projectId: 'noteapp-2fc21',
    storageBucket: 'noteapp-2fc21.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTBtNcWoSDNRJ2GCOiYDo-3FqCRY_8Tw',
    appId: '1:995930544925:ios:76ee10e96b81997a141ff4',
    messagingSenderId: '995930544925',
    projectId: 'noteapp-2fc21',
    storageBucket: 'noteapp-2fc21.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCujLAGFhHA2pfMmOfnZOmdABl33kuFSCc',
    appId: '1:995930544925:web:af2aed95c02b667e141ff4',
    messagingSenderId: '995930544925',
    projectId: 'noteapp-2fc21',
    authDomain: 'noteapp-2fc21.firebaseapp.com',
    storageBucket: 'noteapp-2fc21.appspot.com',
    measurementId: 'G-0SRN2XDRV7',
  );
}
